language: rust
matrix:
  include:
    - rust: stable
    - os: osx

    - env: LIBZ_SYS_STATIC=1
    - env: LIBZ_SYS_STATIC=1
      os: osx

    - rust: stable
      script:
        - cargo generate-lockfile
        - ci/run-docker.sh

    - rust: beta
    - rust: nightly
script:
  - cargo test
  - cargo run --manifest-path systest/Cargo.toml
notifications:
  email:
    on_success: never
